pipeline:
  build-docker:
    image: docker:17.12.1-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - sh build_image.sh
    when:
      event: [push]

  flake8:
    image: python-container:${DRONE_COMMIT_SHA}
    commands:
      - flake8
    when:
      event: [push, pull_request]

  pylint:
    image: python-container:${DRONE_COMMIT_SHA}
    commands:
      - pylint app.py --fail-under=8
    when:
      event: [push, pull_request]

  safety:
    image: python-container:${DRONE_COMMIT_SHA}
    commands:
      - safety check
    when:
      event: [push, pull_request]

  tox:
    image: python-container:${DRONE_COMMIT_SHA}
    commands:
      - tox .
    when:
      event: [push, pull_request]

branches: master
