pipeline:
  build-docker:
    image: docker:17.12.1-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - sh build_image.sh
    when:
      event: [push]

  flake8:
    image: python-container:${DRONE_COMMIT_SHA}
    commands:
      - flake8
    when:
      event: [push, pull_request]

branches: master
